### ISSUE TITLE
HOTP vs TOTP

### ISSUE THREAD

**Issue by zgiles** [cyrozap/python-vipaccess#3]
Hello.
Thank you for a cool program. I was reading your blog post and in it you show a response with a HOTP keyword from Symantec, but in your code it seems to be TOTP, as I would imagine it should be.
Are they mislabeling it in their response as HOTP when actually it's TOTP, or is one able to get a credential either way and you happened to implement the TOTP style?
Could you make your app correctly also get a HOTP key from them instead (so that we can use it with Yubikey for example...) Or is that not how it works. (My understanding is they Symantec should support both.. in some fashion.)
Or is my understanding of TOTP vs HOTP not correct. :) 

Thanks!
-zach

**Comment by cyrozap** [comment]
From the [Wikipedia article on TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm), "TOTP is based on HOTP with a timestamp replacing the incrementing counter." Symantec is therefore technically correct, if unspecific. It may be possible to generate a key for a proper HOTP counter-based token by changing the `TokenModel` to whatever one Symantec uses for their counter-based tokens, but I doubt that since those tokens are provisioned at the factory. However, even if you were able to generate the proper key, I don't believe there is any way to load custom keys onto a standard Yubikey. I haven't tested any of this myself, though, so it may be possible.

**Comment by zgiles** [comment]
Thanks for reading and replying. I see and agree with wikipedia and your assessment of that.. TOTP is HOTP, but a specific type. 
I do believe symantec is capable of supporting non time-base HOTP tokens, due to the fact that they can support a Yubikey, but as you mentioned, they're programmed at the factory. I was also under the impression that the software ones were already precomputed (or something), but with your information, I see that it's actually registered instead which is much more interesting and makes me wonder if they can register more tokens besides just the software TOTP ones..perhaps they have some internal switch for the counter being sequential vs unix time. not sure.
Yubikeys can load a custom key into it, but what I don't know is if the key symantec gives you is the right format, etc etc. and how not to register a non-time based one.
One other interesting comment is that I believe that the button-pressing tokens from symantec are non-time based HOTP. I don't have much evidence for that, just seems to be general consensus from reading.

Anyway, not sure if anyone finds this interesting or if I'm just ranting. I'll reading and testing.

**Comment by zgiles** [comment]
Not sure a next step on this, so I'll close it for now.. no actual issue here.

It someone wants to implement HOTP with VIP for Yubikey by using the API's in this python, that would be awesome.

**Comment by darconeous** [comment]
There is a way to do it, but I'm hesitant to discuss how to do it out of concern that symantec would lock down the service.
